app/models/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    username = StringField("username", validators=[DataRequired()])
    password = PasswordField("passowrd", validators=[DataRequired()])
    remember_me = BooleanField("remember_me")

app/models/tables.py
from app import db

class User(db.Model):
    __tablename__ = "users"
 
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String, unique=True)
    password = db.Column(db.String)
    name = db.Column(db.String)
    email = db.Column(db.String, unique=True)

    @property
    def is_authenticated(self):
        return True

    @property
    def is_active(self):
        return True

    @property
    def is_anonymous(self):
        return False

    def get_id(self):
        return str(self.id)
    
def __init__(self, username, passowrd, name, email):
    self.username = username
    self.passowrd = passowrd
    self.name = name
    self.email = email

def __repr__(self):
    return "<User %r>" % self.username


class Post(db.Model):
    __tablename__ = "posts"

    id = db.Column(db.Integer, primary_key=True)
    content = db.Column(db.Text)
    id_user = db.Column(db.Integer, db.ForeignKey('users.id'))

    user = db.relationship('User', foreign_keys=id_user)
    
    def __init__(self, content, user_id):
        self.content = content
        self.user_id = user_id

class Follow(db.Model):
    __tablename__ = "follow"

    id = db.Column(db.Integer, primary_key=True)
    id_user = db.Column(db.Integer, db.ForeignKey('users.id'))
    id_follower = db.Column(db.Integer, db.ForeignKey('users.id'))

    user = db.relationship('User', foreign_keys=id_user)
    follower = db.relationship('User', foreign_keys=id_follower)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager    

db = SQLAlchemy()
migrate = Migrate()
login_manager = LoginManager()

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


def create_app():
    app = Flask(__name__)
    app.config.from_object('config')

    # Configuração do SQLAlchemy e Flask-Migrate
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app)

    # Importe os modelos SQLAlchemy aqui
    from app.models.tables import Post, User

    #Adiciona rotas
    from app.controllers import default_bp
    app.register_blueprint(default_bp)

    login_manager.login_view = '/login/'  # Substitua 'login' pela rota da sua página de login

    return app

app/controllers/__init__.py
 # app/controllers/__init__.py
from . import default
from .default import default_bp

def init_app(app):
    from . import default  # Importando dentro da função para evitar importação circular
    app.register_blueprint(default.default_bp)

app/controllers/default.py
from flask import Flask, render_template, flash, redirect, url_for
from flask import Blueprint
from app import create_app, db, login_manager
from flask_login import login_user, LoginManager, logout_user

from app.models.tables import User  
from app.models.forms import LoginForm

@login_manager.user_loader
def load_user(id):
    return User.query.filter_by(id=id).first()

default_bp = Blueprint('default', __name__)

'''Função para definir rotas do site  '''
@default_bp.route("/index")
@default_bp.route("/")
def index():
    return render_template('index.html')

@default_bp.route("/login/", methods=["GET","POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user and user.password == form.password.data:
            login_user(user)
            return redirect(url_for("default.index"))
            flash("Logged in.")
        else:
            flash("Invalid login")
    else:
        print(form.errors)
    return render_template('login.html',
                           form=form)

@default_bp.route("/teste/<info>")
@default_bp.route("/teste",defaults={"info": None})
def teste(info):
    r = User.query.filter_by(username="georgia").first()
    r.name = "Georgia"
    db.session.add(r)
    db.session.commit()
    return "ok"




@default_bp.route("/logout")
def logout():
    logout_user()
    flash("Logged out.")
    return redirect(url_for("default.index"))

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

app/templates/base.html
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <link rel="canonical" href="https://getbootstrap.com/docs/3.3/examples/jumbotron-narrow/">

    <title>{% block title %}Twinder{% endblock %}</title>
    
    

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://cdn.jsdelivr.net/npm/html5shiv@3.7.3/dist/html5shiv.min.js"></script>
      <script src="https://cdn.jsdelivr.net/npm/respond.js@1.4.2/dest/respond.min.js"></script>
    <![endif]-->

    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          -ms-user-select: none;
          user-select: none;
        }
  
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style>

<style>
  .form-group,.checkbox, .btn  {
    margin-top: 20px;
    margin-left: 60px;
      
  }   

</style>
    
  </head>  
  <body>
    <div class="container">
        <header class="blog-header py-3">
          <div class="row flex-nowrap justify-content-between align-items-center">
            
            <div class="col-4 text-center">
              <a class="blog-header-logo text-dark" href="#">Twinder</a>
            </div>
            <div class="col-4 d-flex justify-content-end align-items-center">
              <a class="text-muted" href="#">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="mx-3" role="img" viewBox="0 0 24 24" focusable="false"><title>Search</title><circle cx="10.5" cy="10.5" r="7.5"/><path d="M21 21l-5.2-5.2"/></svg>
              </a>
              <a class="btn btn-sm btn-outline-secondary" href="#">
                {% if current_user.is_authenticated %}
                  <li><a href="{{ url_for('default.logout')}}"> Logout</a> </li>
                {% else %}
                  <li><a href="{{ url_for('default.login') }}">Login</a>
                {% endif %}
                  </li>
            </a>
            </div>
          </div>
   </header>
   <div class="nav-scroller py-1 mb-2">
    <nav class="nav d-flex justify-content-between">
      <a class="p-2 text-muted" href="#">World</a>
      <a class="p-2 text-muted" href="#">Technology</a>
      <a class="p-2 text-muted" href="#">Design</a>
      <a class="p-2 text-muted" href="#">Culture</a>
      <a class="p-2 text-muted" href="#">Business</a>
      <a class="p-2 text-muted" href="#">Politics</a>
      <a class="p-2 text-muted" href="#">Opinion</a>
      <a class="p-2 text-muted" href="#">Science</a>
      <a class="p-2 text-muted" href="#">Health</a>
      <a class="p-2 text-muted" href="#">Style</a>
      <a class="p-2 text-muted" href="#">Travel</a>
    </nav>
  </div>    

      <div>
       
        {% with messages = get_flashed_messages() %}
        
            {% if messages %}
            <div class="alert alert-warning">
              <ul class=flashes>
                
              {% for message in messages %}
                <li>{{ message }}</li>
              {% endfor %}
              </ul>
            {% endif %}
          {% endwith %}
          </div>
      </div>
      {% block content %}
      {% endblock %}
  
  <style>
    .footer {
        position: fixed;
        left: 3;
        bottom: 0;
        width: 100%;
        text-align: left;
        padding-left: 2px;
    }
  </style>
  <footer class="footer" style="display: block;">

    <p>Developed by felipmarqs</p>

  </footer>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>

  </body>

  </html>

app/templates/index.html
{% extends 'base.html' %}

{% block title %} {{ super() }}- Index {% endblock %}

{% block content %}
<div class="jumbotron">
    <h1>Bem vindo ao Twinder</h1>
    <p class="lead">Este projeto é um estudo de Flask com objetivo de criar um site similar ao Twitter.</p>
    <p><a class="btn btn-lg btn-success" href="#" role="button">Sign up today</a></p>
  </div>

  
  {% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %} {{ super() }}- Login {% endblock %}

{% block login %} Login {% endblock %}




{% block content %}
<div class="col-md-4 col-offset-3">


<form action="" method="POST">
    {{ form.csrf_token }}

    <div class="form-group">
        <label>Username</label>
        {{ form.username(class="form-control",
        placeholder="seu_usuario") }}
        {% if form.errors.username %}
        <div>
            {% for e in form.errors.passowrd %}
                <li>{{ e }}</li>
            {% endfor %}
            {{ form.errors.username }}
          </div>
        {% endif %}
    </div>
    <div class="form-group">
        <label>Password</label>
        {{ form.password(class="form-control") }}
    </div>
    <div class="checkbox">   
        <label>
            {{ form.remember_me }} Remember me
        </label>     
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
</form>

</div>

{% endblock %}